FROM ruby

RUN gem install uber_fast_excel

ARG TRAVIS_COMMIT
ARG TRAVIS_BRANCH
ARG GIT_REPO

RUN echo "source 'https://rubygems.org'" > Gemfile

RUN [ -z "$TRAVIS_COMMIT" ] && \
  echo "gem 'uber_fast_excel', git: 'https://github.com/willfish/fast_excel.git', require: 'fast_excel'" >> Gemfile || true
RUN [ -z "$TRAVIS_COMMIT" ] || \
  echo "gem 'uber_fast_excel', git: 'https://github.com/${GIT_REPO}.git', branch: '$TRAVIS_BRANCH', ref: '$TRAVIS_COMMIT', require: 'fast_excel'" >> Gemfile

RUN cat Gemfile
RUN bundle
