name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.3
      - uses: ruby/setup-ruby@v1.313.0
        with:
          ruby-version: "3.4"

      - run: bundle config set --local without 'benchmarks'
      - run: bundle install
      - run: make
      - run: make install
      - run: rake test
      - run: rake examples
      - run: gem build uber_fast_excel.gemspec

      - name: Publish to RubyGems
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: gem push uber_fast_excel-*.gem
